# locators.py

class Orange_Locators:
    username_locator = 'username'
    password_locator = 'password'
    submitBox_locator = '/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'
    searchbox_locator = '/html/body/div/div[1]/div[1]/aside/nav/div[2]/div/div/input'
    a = 'Admin'
    b = 'PIM'
    c = 'Leave'
    d = 'Time'
    e = 'Recruitment'
    f = 'My info'
    g = 'Performance'
    h = 'Dashboard'
    i = 'Directory'
    j = 'Maintenance'
    k = 'Buzz'
    admin_button = '/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a'
    user_management_header = '/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[1]/span'
    users_button = '/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[1]/ul/li/a'
    userrole_dropdown = '/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div/div[2]/i'
    status_dropdown = '/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div/div[1]'
    Admin = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/span'
    Enabled = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div[2]/div[2]/span'
    ESS = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[3]/span'
    Disabled = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div[2]/div[3]/span'
    username_input_box = 'username' # Name
    password_input_box = 'password' # Name
    submit_button = '/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'
    PIM_button = '/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a'
    add_button = '/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[1]/button'
    add_employee_button ='/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/a'
    first_name_locator = 'firstName' # Name
    middle_name_locator = 'middleName' # Name
    last_name_locator = 'lastName' # Name
    first_name = 'Faiz'
    middle_name ='Ali'
    last_name = 'Khan'
    radio_button_1 = '/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[2]/div/label/span'
    username_01 = '/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[1]/div/div[2]/input'
    password_01 ='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/input'
    confirm_password = '/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[2]/div/div[2]/input'
    save_button_2 = '/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]'
    username_field = 'hello'
    password_field = 'Asdf@1234'
    password_field_2 = 'Asdf@1234'
    employee_list_button = '/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/a'
    employee_id_locator = '/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/input'
    searchbox_locator ='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[2]/button[2]'
    id_field = '0272'
    id_locator = '/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[2]/div'
    Personal_Details = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[1]/a'
    Contact_Details = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[2]/a'
    Emergency_Contacts = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[3]/a'
    Dependents = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[4]/a'
    Immigration = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[5]/a'
    Job = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[6]/a'
    Salary = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[7]/a'
    TaxExemptions = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[8]/a'
    Report_to = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[9]/a'
    Qualifications = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[10]/a'
    Memberships = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[11]/a'
    Driving_License_field = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input'
    Driving_License_Number = '123456789'
    Driving_License_Expiry = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[2]/div/div[2]/div/div/input'
    Driving_License_ExpiryDate = '2023-05-21'
    SSN_Number = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[1]/div/div[2]/input'
    Nationality_Dropdown = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[1]/div/div[2]/div/div[1]/div[1]'
    Indian_Select = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[1]/div/div[2]/div/div[2]/div[83]/span'
    Marital_Status_field = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[2]/div/div[2]/div/div/div[1]'
    Marital_Status_Select_Button = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[2]/div/div[2]/div/div[2]/div[2]/span'
    DateofBirth_locator ='/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[1]/div/div[2]/div/div/input'
    DateofBirth_field = '1994-08-18'
    Gender_button = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/label'
    Military_Service = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div/div[1]/div/div[2]/input'
    Military_field = 'NO'
    save_button_3 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button'
    Street_01 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    Street_02 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    City = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/input'
    State = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/input'
    Country_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div/div[1]'
      
    Country_Selector = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div[2]/div[2]/span'
    Telephone = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input'
    Mobile = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input'
    Work = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input'
    Email = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/input'
    save_button_4 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button'
    street_1 = 'Near metro station ameerpet'
    street_2 = 'Lane 1 house no-2'
    city = 'Hyderabad'
    State_1 = 'Telangana'
    Home_Phone = '1234567890'
    Mobile_Phone = '0987654321'
    Profession = '100'
    Work_email = 'skhazee13@guvi.in'
    Add_button_1 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button'
    Relation = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    RelationShip = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    Telephone_01 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input'
    Mobile_01 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input'
    save_button_5 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]'
    Relation_Name = 'Mohammad Shaik'
    Relation_with = 'Father'
    Home_Phone_01 = '1234567890'
    Mobile_Phone_01 = '0987654321'
    Dependent = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    Dependents = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[4]/a'
    Add_button_2 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button/i'
    Dependent_Name = 'Mohammad Shaik'
    Relation_Dropdown = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]'
    Relation_Option = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[3]/span'
    Specify_Inputbox = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/input'
    Specify_Field = 'Father'
    DOB = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div/div/div[2]/div/div/input'
    DOB_field = '1972-03-22'
    save_button_6 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]'
    Joined_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/input'
    Joined_Date = '2020-02-01'
    Job_Title = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]'
    Profession = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[18]/span'
    Job_Category = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div/div[1]'
    Category_profession ='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div[2]/div[7]/span'
    Sub_Unit = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/div/div/div[1]'
    Sub_Unit_Profession = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/div/div[2]/div[5]/span'
    Location_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div/div[1]'
    Location_tab = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div[2]/div[3]/span'
    Employee_Status_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[7]/div/div[2]/div/div/div[1]'
    Employee_Status = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[7]/div/div[2]/div/div[2]/div[2]/span'
    Contact_Details_button = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/label/span'
    Cotract_Start = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/div/div/input'
    Cotract_Start_date = '2020-02-01'
    Cotract_End = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[2]/div/div[2]/div/div/input'
    Cotract_End_date = '2023-03-20'
    save_button_7 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button'
    Employee_Termination = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button'
    Date_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[1]/div/div[2]/div/div/input'
    Termination_Date = '2023-03-20'
    Reason_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[2]/div/div[2]/div/div/div[1]'
    Termination_Reason = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[2]/div/div[2]/div/div[2]/div[3]/span'
    Note_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[3]/div/div[2]/textarea'
    Note = 'Good Bye'
    Save_button_8 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[4]/button[2]'
    Activate_Termination = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button'
    Add_button_3 = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button'
    Salary_Locator = '/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    Salary_1 = '100000'
    Pay_Grade_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]'
    Pay_Grade ='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[5]/span'
    Pay_Frequency_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/div/div/div[1]'
    Pay_Frequency = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/div/div[2]/div[4]/span'
    Currency_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div/div[1]'
    Currency = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div[2]/div[63]/span'
    Amount_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input'
    Amount = '70000'
    Save_button_9 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button[2]'
    Status_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/div[1]'
    Status = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div[2]/div[2]/span'
    Examptions_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    Examptions = '15'
    State_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/div/div/div[1]'
    State = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/div/div[2]/div[3]/span'
    Status_Locator_1 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/div/div/div[1]'
    Status_1 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/span'
    Examptions_Locator_1 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input'
    Examptions_1 = '25'
    Un_Employeement_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[4]/div/div[2]/div/div/div[1]'
    Un_Employeement_State ='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[4]/div/div[2]/div/div[2]/div[5]/span'
    Work_State_Locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[5]/div/div[2]/div/div/div[1]'
    Work_State = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[5]/div/div[2]/div/div[2]/div[3]/span'
    Save_button_10 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button'
    
   
